### ISSUE TITLE
Productivity tracker

### ISSUE THREAD

**Issue by Clouddoggo** [Clouddoggo/main#2]
**v1.2:** Set up parser for command to track productivity in a day.

- [x] Add stop and start timer classes
- [x] Add stop and start command parser classes and to JelphabotParser
- [x] Add productivity model for easy migration to view
- [x] Store duration taken for task completion as Task attribute (?)
- [x] Lock commands for adding and deleting tasks when timer is running.
- [x] On exit, if timer is not stopped, discard recorded time.

**v1.3:** Add options to track productivity in a week/month. Visualisation to be responsive and show the different levels of productivity.
- [x] Set up ProductivityPanel to display overall productivity in a day.

**Comment by Clouddoggo** [comment]
v1.4 Jelphabot criticism and compliment as encouragement when % of tasks completed
